// clang-format on
#include "quick/utils/XorBitant.hh"

#include <algorithm>
#include <chrono>
#include <gtest/gtest.h>
#include <map>
#include <print>
#include <random>
#include <ranges>
#include <thread>
// clang-format off

class XorBitantTest : public ::testing::Test
{
protected:
    static constexpr int min_num = 0;
    static constexpr int max_num = 6;

    void generateHistogram(XorBitant& xor_gen, const std::string& seed_type)
    {
        std::map<int, int> hist;
        std::uniform_int_distribution dist(min_num, max_num);

        std::ranges::for_each(std::views::iota(0, 10000), [&xor_gen, &hist, &dist](auto) { ++hist[dist(xor_gen)]; });
        std::println("Histogram of random numbers ({}-{}) generated by XorBitant ({} seed):", min_num, max_num, seed_type);
        std::ranges::for_each(hist, [](const auto &pair) {
            std::print("{:3} | ", pair.first);
            for (int i = 0; i < pair.second / 100; ++i)
                std::print("*");
            std::println(" ({})", pair.second);
        });
    }

    void testRandomnessAndShuffling(XorBitant& xor_gen)
    {
        std::uniform_int_distribution dist(min_num, max_num);

        // Using XorBitant with distribution
        std::println("Random numbers with XorBitant:");
        std::ranges::for_each(std::views::iota(0) | std::views::take(10),
                              [&dist, &xor_gen](auto) { std::print("{} ", dist(xor_gen)); });

        // Shuffle a range/vector
        std::println("\n\nOriginal:");
        auto rng = std::views::iota(0, 10) | std::ranges::to<std::vector>();
        std::ranges::for_each(rng, [](const int el) { std::print("{} ", el); });

        std::println("\nAfter shuffling with XorBitant:");
        std::ranges::shuffle(rng, xor_gen);
        std::ranges::for_each(rng, [](const int el) { std::print("{} ", el); });
        std::println("");
    }
};

TEST_F(XorBitantTest, SingleClockSeed)
{
    std::uint64_t single_clock_seed = std::chrono::steady_clock::now().time_since_epoch().count();
    XorBitant xor_gen{single_clock_seed};
    
    generateHistogram(xor_gen, "single clock");
    testRandomnessAndShuffling(xor_gen);
}

TEST_F(XorBitantTest, DoubleClockSeed)
{
    std::uint64_t double_clock_seed = std::chrono::steady_clock::now().time_since_epoch().count() ^
                                      std::chrono::system_clock::now().time_since_epoch().count();
    XorBitant xor_gen{double_clock_seed};
    
    generateHistogram(xor_gen, "double clock");
    testRandomnessAndShuffling(xor_gen);
}

TEST_F(XorBitantTest, ThreadDoubleClockSeed)
{
    std::uint64_t thread_double_clock_seed = std::chrono::steady_clock::now().time_since_epoch().count() ^
                                             std::chrono::system_clock::now().time_since_epoch().count() ^
                                             std::hash<std::thread::id>{}(std::this_thread::get_id());
    XorBitant xor_gen{thread_double_clock_seed};
    
    generateHistogram(xor_gen, "thread + double clock");
    testRandomnessAndShuffling(xor_gen);
}